process.env.LOG_LEVEL = "error";

import { before, beforeEach, mock, test } from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";

let writes: Array<{ path: string; content: string }> = [];

function alphaWord(index: number): string {
  const letters = "abcdefghijklmnopqrstuvwxyz";
  let value = index;
  let out = "w";
  do {
    out += letters[value % letters.length];
    value = Math.floor(value / letters.length);
  } while (value > 0);
  return out;
}

before(() => {
  mock.module("node:fs", {
    namedExports: {
      writeFileSync: (path: string, content: string) => {
        writes.push({ path, content });
      },
    },
  });
});

beforeEach(() => {
  writes = [];
});

test("wordfreq rank helpers normalize, filter, and format output", async () => {
  const { normalizeWord, buildTopWords, renderWordList, renderOutput } = await import(
    "../scripts/generate-wordfreq-ranks"
  );

  assert.equal(normalizeWord("Word"), "word");
  assert.equal(normalizeWord("3word"), null);
  assert.equal(normalizeWord("b"), null);
  assert.equal(normalizeWord("i"), "i");

  const rows = Array.from({ length: 10_200 }, (_, index) => [alphaWord(index), -index] as [string, number]);
  const top = buildTopWords(rows);
  assert.equal(top.length, 10_000);
  assert.throws(() => buildTopWords([["alpha", -1]]), /Expected at least 10000 filtered words/);

  const list = renderWordList(["alpha", "beta", "gamma", "delta"]);
  assert.match(list, /"alpha"/);
  assert.match(list, /"delta"/);

  const output = renderOutput('  "alpha", "beta"');
  assert.match(output, /Generated by scripts\/generate-wordfreq-ranks\.ts/);
  assert.match(output, /WORDFREQ_EN_TOP_10K/);
});

test("wordfreq fetchRows validates HTTP status and payload shape", async () => {
  const { fetchRows } = await import("../scripts/generate-wordfreq-ranks");

  const originalFetch = globalThis.fetch;
  try {
    globalThis.fetch = ((async () => ({
      ok: false,
      status: 500,
      statusText: "boom",
    })) as unknown) as typeof fetch;
    await assert.rejects(() => fetchRows(), /Failed to fetch/);

    globalThis.fetch = ((async () => ({ ok: true, json: async () => ({}) })) as unknown) as typeof fetch;
    await assert.rejects(() => fetchRows(), /JSON array/);

    globalThis.fetch = ((async () => ({
      ok: true,
      json: async () => [["alpha", -1], ["beta", -2]],
    })) as unknown) as typeof fetch;
    const rows = await fetchRows();
    assert.deepEqual(rows, [["alpha", -1], ["beta", -2]]);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test("wordfreq main writes generated rank module", async () => {
  const { main } = await import("../scripts/generate-wordfreq-ranks");

  const originalFetch = globalThis.fetch;
  const originalLog = console.log;
  const logs: string[] = [];
  console.log = ((...args: unknown[]) => logs.push(args.join(" "))) as typeof console.log;

  try {
    globalThis.fetch = ((async () => ({
      ok: true,
      json: async () =>
        Array.from({ length: 10_500 }, (_, index) => [alphaWord(index), -index]),
    })) as unknown) as typeof fetch;
    await main();
  } finally {
    globalThis.fetch = originalFetch;
    console.log = originalLog;
  }

  assert.equal(writes.length, 1);
  assert.match(writes[0]?.path ?? "", /src\/data\/wordfreq-en-ranks\.ts$/);
  assert.match(writes[0]?.content ?? "", /WORDFREQ_EN_TOP_10K/);
  assert.match(logs.join("\n"), /Wrote 10000 words/);
});

test("wordfreq generator entrypoint executes runScript when module is main", async () => {
  const scriptUrl = new URL("../scripts/generate-wordfreq-ranks.ts", import.meta.url).href;
  const scriptPath = fileURLToPath(scriptUrl);
  const originalArgv = process.argv;
  const originalExit = process.exit;
  const originalFetch = globalThis.fetch;
  const originalLog = console.log;
  const originalError = console.error;
  const exits: Array<number | undefined> = [];

  let resolveExit: (() => void) | null = null;
  const exited = new Promise<void>((resolve) => {
    resolveExit = resolve;
  });

  process.argv = [process.execPath, scriptPath];
  process.exit = ((code?: string | number | null | undefined): never => {
    exits.push(typeof code === "number" ? code : code == null ? 0 : Number(code));
    resolveExit?.();
    return undefined as never;
  }) as typeof process.exit;
  globalThis.fetch = ((async () => ({
    ok: true,
    json: async () => Array.from({ length: 10_500 }, (_, index) => [alphaWord(index), -index]),
  })) as unknown) as typeof fetch;
  console.log = (() => undefined) as typeof console.log;
  console.error = (() => undefined) as typeof console.error;

  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    const { runAsCli } = await import("../scripts/generate-wordfreq-ranks");
    runAsCli(scriptUrl);
    await Promise.race([
      exited,
      new Promise<void>((_, reject) => {
        timer = setTimeout(() => reject(new Error("wordfreq entrypoint did not exit")), 1000);
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
    process.argv = originalArgv;
    process.exit = originalExit;
    globalThis.fetch = originalFetch;
    console.log = originalLog;
    console.error = originalError;
  }

  assert.deepEqual(exits, [0]);
});
