/**
 * Training corpus for the local Naive-Bayes ad/article quality classifier
 * (Issue #739 follow-up).
 *
 * GENERATED FILE — the `HARVESTED_*` arrays below are produced by
 * `scripts/build-quality-corpus.ts`, which live-harvests real, heuristic-labeled
 * scrapes (positives graded `ok` by `checkContentQuality`) and real/synthetic
 * boilerplate + ad copy (negatives). Re-run the builder to regenerate, then
 * re-run `scripts/train-quality-classifier.ts` to rebuild the model JSON.
 *
 * The hand-curated SEED samples are imported from
 * `quality-classifier-seed-corpus.ts` and are always preserved. Edit seeds
 * there; do NOT hand-edit the harvested arrays here (they are overwritten).
 *
 * @server-only — only consumed by the training script and the (server-only)
 * classifier module.
 *
 * COPYRIGHT / PRIVACY: harvested positives are SHORT excerpts only (truncated to
 * ≤ ~50 words / first 1-2 sentences) of already-public article prose — never
 * full article bodies. Negatives are generic, non-creative boilerplate
 * (newsletter / cookie / nav / related blocks) and synthetic ad copy. No
 * user-private content is ever stored here.
 */

import {
  SEED_ARTICLE_SAMPLES,
  SEED_AD_SAMPLES,
} from "@/lib/scraper/quality-classifier-seed-corpus";

/** Live-harvested article-prose excerpts (SHORT, ≤ ~50 words each). */
export const HARVESTED_ARTICLE_SAMPLES: readonly string[] = [
  "LA GUAIRA, Venezuela — The increasingly desperate search for survivors in Venezuela entered a third day Saturday as people dug through the rubble of collapsed homes and apartment buildings after the devastating one-two punch of 7. 2 and 7.",
  "The Iran war has led to higher prices at the gas pump. Gas prices in the United States, up by nearly 40% since the U.",
  "Secretary of State Marco Rubio, along with Israel and Lebanon’s ambassadors, announced a framework agreement Friday that was described as a first step toward peace following months of conflict between Israel and the Lebanese militant group Hezbollah. The officials did not share details on the agreement that was signed by…",
  "A trickle of marine traffic was passing through the Strait of Hormuz on Friday despite an attack on a ship in the vital waterway a day earlier, as Iran reiterated its warnings for ships to follow a Tehran-approved route. A flow of vessels transiting via an alternative route close to…",
  "The second earthquake that hit Venezuela on Wednesday started rumbling before the first had even concluded. Their onsets were separated by just 39 seconds.",
  "Summer is officially here, and it’s kicking off with an extreme heat dome that’s scorching much of the United States. According to the National Oceanic and Atmospheric Administration's Weather Prediction Center, two heat domes are set to combine.",
  "It’s the fourth leading type of cancer for women across the world, but new research shows that cervical cancer has met its match. The human papillomavirus (HPV) vaccine, Gardisil 9 , was the subject of a just-published study in the U.",
  "Stargazers might have their sights set on August’s total solar eclipse in Europe and the annual Perseid meteor shower—but don’t sleep on July’s nightscapes. This month offers a host of cosmic marvels, including planet-moon couplings and two simultaneous meteor showers.",
  "Water levels were so low on the Colorado River , Travis Francis knew he needed to shock some fish. On a recent June morning, Francis, a U.",
  "National Geographic Explorer and photographer Mackenzie Calle has been making space exploration the subject of her photographic work for five years. In October 2025, she got a fascinating behind-the-scenes look at astronaut space training when she spent two weeks as a crew member at the Mars Desert Research Station (MDRS)…",
  "June brings summer to the northern hemisphere, and with it comes a host of celestial wonders, from planet meetups to a meteor shower. The month also offers prime viewing of the dense, star-filled core of the Milky Way galaxy, particularly from dark-sky getaways .",
  "Inside a South Korean laboratory for sunscreen products, Dasol Song, 39, walked alongside a long wall of colorful bottles and tubes, displayed like trophies celebrating the latest advances in UV protection. Around him, fellow researchers sifted through shelves of beakers and plastic containers.",
  "Record-breaking heat and humidity are already upon us at the start of what is predicted to be a scorcher of a summer. Our cities, with their dark, asphalt surfaces, exhaust-emitting vehicles, and heat-trapping buildings, feel these temperatures the most.",
  "Score a victory for the city of Seattle, whose World Cup host committee, LGBTQ+ community, and body politic declined to give in to demands that its World Cup Pride Match , held Friday night, go away. Because if that had happened, an Iranian fan would not have asked to take…",
  "Time ideas Jun 27, 2026 11:00 AM CUT Photo-Illustration by TIME; Dan Kitwood—Getty Images (2) by Jun 27, 2026 11:00 AM CUT It has become an all too familiar ritual in the United Kingdom. A somber Prime Minister emerges, delivers a list of achievements in office—some real, others less so—and…",
  "Relief efforts are underway after Venezuela was struck by two successive earthquakes on Wednesday evening. At least 920 people have died, with 3,360 injured, said Jorge Rodríguez, the president of the country’s National Assembly, on Friday.",
  "A controversial proposal that would impose a one-time 5% tax on the wealth of billionaires in California will be put before voters in November after Gov. Gavin Newsom failed to reach a deal with the union behind the measure by the deadline to withdraw ballot initiatives on Thursday.",
  "Many live in quiet fear that AI will someday be, if not the death of art itself, then at least of the human artist’s livelihood. Between Hollywood screenwriters taking to the streets to protect their jobs from large language models and robot artists like Ai-Da fetching millions at auction, the…",
  "At the beginning of 2026, to kick off this year’s celebration of the 250th birthday of the United States, we published a list of America’s Most Iconic Companies . Based on a national survey, conducted with our research partner Statista, we ranked companies—including Ford, Apple, the Walt Disney Co.",
  "Prestige TV is always thinking bigger. Especially if it gets popular enough to command a hefty budget, an ambitious show will expand its playing field and reach for real-world resonance.",
  "America was born into geopolitics . The Republic’s first decades were shaped by the rivalry between the British and French empires, and George Washington used his farewell address to warn his countrymen against permanent foreign entanglements.",
  "In the hours since the Supreme Court announced it would allow the Trump administration to end temporary protected status for immigrants from Haiti and Syria, the potential consequences have ricocheted through American communities. Panic and chaos have set in.",
  "DENVER — The insurgency rocking the Democratic Party is set to reach mile-high heights on Tuesday, with a trio of primaries in Colorado giving voters a chance to express their anger with the party’s establishment. The Colorado races are distinct: an ideological battle for a safe blue House seat in…",
  "MS Now host Jacob Soboroff suggested Vice President JD Vance may have revealed more than he intended with a recent comment. Vance, speaking Thursday at the Nixon Library in Yorba Linda, California, said the Watergate scandal that ultimately led to the downfall of former President Richard Nixon just wouldn’t be…",
  "President Donald Trump called Tuesday’s primary election wins of progressive candidates backed by New York City Mayor Zohran Mamdani “the greatest threat to our country since its founding,” smearing them on Friday as communists who “will kill your people. ” Trump was speaking at the Faith & Freedom Coalition’s 2026…",
  "It’s just an empty field — a small, mundane feature of a form that someone designed, probably years ago, without thinking about who would eventually be sitting in a plastic chair trying to fill it out. And yet there you are, your kid in a hospital bed next to you…",
  "“Real Time” host Bill Maher , speaking with Vice President JD Vance Friday, maligned the recent election victories in New York by three democratic socialist candidates and said his vote may soon land with a different party. “If this is where the Democratic Party is going, with the democratic socialists.",
  "Larry David was so precious about his scripts for his new HBO sketch show, “Life, Larry and the Pursuit of Unhappiness,” that not even former President Barack Obama could curb his enthusiasm — and was swiftly shut down by the comedian for trying to give him some notes. The duo…",
  "SEATTLE ― The emotions were still raw for Iran players and their coach long after the final whistle of the team’s 1-1 draw against Egypt in their group-stage finale at Seattle Stadium on Friday night. Seeking to advance out of the group stage for the first time in their World…",
  "Jonathan Majors ’ acting career has struggled in the wake of his 2023 assault conviction , and his latest film doesn’t seem to be doing him any favors for a supposed mainstream comeback. Earlier this year, the former Marvel star, 36, was announced as part of the cast of an…",
  "People search through the rubble unprotected, using whatever they can Bare hands and shovels shift through the rubble, while a drone scans overhead. Every moment, every action matters.",
  "Each morning that Venezuelans wake to the aftermath of the dual earthquakes, it is a little darker, a little grimmer. It means another night in which prayers for the miraculous recovery of missing loved ones went unanswered, in which the fitful sleep of the survivors is interrupted by nightmares of…",
  "The US has conducted new strikes on Iran, following a drone attack on a Panama-flagged vessel in the Strait of Hormuz on Saturday. US Central Command (Centcom) said it hit multiple targets across Iran in direct response to \"continued aggression\" against commercial shipping.",
  "Israeli air strikes in Lebanon have killed one person, the country's health ministry said, a day after the two countries signed a deal aimed at paving the way to a lasting peace. Lebanon's state news agency said an Israeli drone hit the southern town of Nabatieh al-Fawqa, and later reported…",
  "The story of the Koreas, according to popular belief, begins on Mount Paektu - a mountain located on the China-North Korea border that is said to be the birthplace of Dangun, the mythical founder of what became Korea's first kingdom. Thousands of years later, Kim Il Sung - the founder…",
  "Europe has experienced another day of extreme heat with temperature records being broken across the continent again on Saturday. Germany set a new all-time high for the second day in a row, as temperatures reached 41.",
  "The Trump administration has unveiled a new limited edition US passport design featuring a photo of President Donald Trump to commemorate America's 250th birthday . In a post on social media on Friday, Trump shared a photo of the passport's newly designed pages, one that includes an image of himself…",
  "A Texas education panel has approved plans to make Bible stories mandatory for all five million public school students in the state, sparking a row about separation of church and state. The required readings, which don't come into effect until 2030, include Bible passages about Adam and Eve and from…",
  "Burkina Faso's military junta has broken off diplomatic ties with France, accusing Paris of persistently acting against its national interests. Relations between Burkina Faso and its former colonial ruler worsened after Capt Ibrahim Traore seized power in a coup in 2022 and pursued largely anti-Western policies.",
  "Relations between Italy's prime minister and President Trump have worsened considerably since 2025 There is an AI-generated meme doing the rounds on social media in Italy that shows Giorgia Meloni doing all the things you might expect from someone fresh out of a tough break-up. In one fake photo she…",
  "A Vietnam Veteran Collected Fossils for 66 Years. One, Mislabeled ‘Baby Lamprey,’ Made Paleontologists Reconsider How Vertebrates Moved From Water to Land The fossil turned out to be a hatchling of a crocodile-like creature, and it suggests, according to a new study, that early animals did not use metamorphosis to…",
  "When a Team of Meteorologists and Combat Pilots Set Out to Understand Thunderstorms, They Made Flying Safer for Everyone The sky was a very dangerous place in the early days of commercial aviation. By flying into storms to learn how they worked, these experts made air travel and weather forecasting…",
  "The Operating Room Where Anesthesia Was First Demonstrated Is Now a Landmark. But for the Men Who Claimed Credit, There Was Much Misery Medical procedures used to be a scream-filled endurance test until doctors at this Boston institution learned to tame the pain of patients The “Ether Dome” at Massachusetts…",
  "The Kepler telescope changed how we saw the sky. It’s just one of the devices we’ve sent out beyond the reach of humans to search our solar system An illustration of all 726 solar systems depicting planets confirmed as of October 30, 2018, the end of Kepler’s life span.",
  "Inks created with a patient’s own cells may one day help the body regrow tissues Andrea Teagle, Knowable Magazine June 24, 2026 Cells suspended in a water-based gel make up the “ink” in this 3D printer. Wake Forest Institute for Regenerative Medicine A hand touches a scalding hot plate, sharp…",
  "Light-activated therapies may offer a solution to slow-healing lesions common in diabetics and burn victims Zunnash Khan, Knowable Magazine June 17, 2026 Slow-healing wounds, especially in diabetics and burn victims, can become infected with antibiotic-resistant bacteria. Light-activated nanomaterials offer a potential new way to clear the infection and accelerate wound…",
  "On the morning of January 8, 1790, the first president of the United States strode into Federal Hall in New York City to deliver a speech that would become known as the State of the Union address. Dressed in an elegant dark suit, George Washington outlined his priorities for the…",
  "What’s Behind Steven Spielberg’s Lifelong Obsession With Flying Saucers and Extraterrestrial Visitors? Half a century after “Close Encounters of the Third Kind,” the director returns to the subject of UFOs with “Disclosure Day.",
  "‘Stupid Hot’: Heat Waves Muddle the Minds of Animals and Humans as Confusion and Aggression Seem to Rise With the Temperature Wide-ranging research suggests that as temperatures increase, some creatures pick fights while others struggle to learn. The findings hint at consequences that may ripple through ecosystems Marta Zaraska, Knowable…",
  "Some Placeholder Text CREDIT: NAME Institution Name Some Placeholder Text CREDIT: NAME Institution Name CREDIT: STEPHAN SCHMITZ / THEISPOT Scientists are exploring how AI tools could help identify misinformation online. In an epidemic of online misinformation, experts look to artificial intelligence to help sort fact from fiction By Katarina Zimmer…",
  "Some Placeholder Text CREDIT: NAME Institution Name Some Placeholder Text CREDIT: NAME Institution Name CREDIT: ISTOCK. COM / DESIGN CELLS The link between smell and brain health is complicated.",
  "Some Placeholder Text CREDIT: NAME Institution Name Some Placeholder Text CREDIT: NAME Institution Name CREDIT: IYAD RAHWAN As AI systems get more responsibilities, they may soon be facing moral dilemmas just like humans do, as evoked by this series of paintings by computer scientist Iyad Rahwan. Q&A — Computer scientist…",
  "Some Placeholder Text CREDIT: NAME Institution Name Some Placeholder Text CREDIT: NAME Institution Name CREDIT: WAKE FOREST INSTITUTE FOR REGENERATIVE MEDICINE Cells suspended in a water-based gel make up the “ink” in this 3D printer. Inks created with a patient’s own cells might one day help the body regrow tissues…",
  "Some Placeholder Text CREDIT: NAME Institution Name Some Placeholder Text CREDIT: NAME Institution Name CREDIT: WORLDSTOCKSTUDIO / SHUTTERSTOCK Dharavi, the largest informal settlement in Mumbai, India, is densely packed with homes, small business and informal industries. As temperatures rise, it is the poor who suffer most.",
  "Some Placeholder Text CREDIT: NAME Institution Name Some Placeholder Text CREDIT: NAME Institution Name CREDIT: EDWARD HOPPER / PUBLIC DOMAIN Our company-seeking behavior is governed by specific regions in the brain. Neuroscientists are discovering that spending time with others may be a basic biological necessity, like need for food or…",
  "Some Placeholder Text CREDIT: NAME Institution Name Some Placeholder Text CREDIT: NAME Institution Name CREDIT: EVERGLADES NATIONAL PARK, FLORIDA Mosquitoes drink blood from the tail of a hispid cotton rat in the Everglades. Critters that dine on flesh and waste also consume the animal’s DNA.",
  "Some Placeholder Text CREDIT: NAME Institution Name Some Placeholder Text CREDIT: NAME Institution Name CREDIT: SUNNU REBECCA CHOI Studies are documenting how heat influences behavior and learning in a variety of animals. As temperatures rise, some creatures pick fights while others struggle to learn.",
  "What happens when tropical rainforest patches get isolated on mountaintops that have different environments from the valleys? For example, the largest rainforest in Southern Africa spans about 30 square miles on Mozambique’s Mount Mabu , which towers over the savanna below.",
  "Marie Curie is an icon of science. She was not only the first woman to win a Nobel Prize, in 1903, she is still the only person to win two science Nobels in different fields—her 1903 win was in Physics while her 1911 medal was in Chemistry.",
  "If you’ve ever wondered why so many objects in the night sky are designated with an “M” followed by a number, you can thank Charles Messier. This 18th-century French astronomer had a singular obsession—finding comets—so much so that King Louis XV called him le furet des comètes or “comet ferret.",
  "Two decades ago, American journalist and author Richard Louv coined the term “nature deficit disorder” in his book The Last Child in the Woods. Back then, few scientists had studied how alienation from nature affects human health, for children or adults, but in the years since, this question has drawn…",
  "Neanderthals thrived on Earth for 200,000 years, living in Central Asia, throughout Europe, and into the Middle East. Around 40,000 years ago they mysteriously vanished.",
  "Billions of years ago, water flowed on Mars, and NASA’s Perseverance rover has been trundling along an ancient riverbed flowing into Jezero Crater searching for any signs of life that could have thrived there. In September of 2025, it uncovered a possible biosignature in the Bright Angel rock formation.",
  "In an eyebrow-raising Facebook post in 2013, paleontologist Lee Berger made an interesting overture . He needed a team of people with paleontology and caving experience, with one other stipulation: They had to be small.",
  "After college, I went backpacking through Africa, and at the Khartoum airport in Sudan I met an American guy named Chris. We explored together for a few days and went our separate ways.",
  "Artificial intelligence is rapidly reshaping retail, but not in the ways consumers might immediately notice. The biggest transformation may not be flashy virtual try-ons or chatbot shopping assistants, but in how decisions are made behind the scenes: how products surface in search results, how inventory moves through supply chains, how…",
  "Plus: Anthropic says Alibaba “illicitly” extracted Claude’s capabilities . June 25, 2026 Europe’s extreme heat is shutting down power plants Europe is in the middle of a record-breaking heat wave, and the grid is being pushed to its limits as people turn to fans and air-conditioning to try to stay…",
  "Summer is getting hotter, and utilities need to adapt. June 25, 2026 Pablo Blazquez Dominguez/Getty It’s been hard to look away from headlines about the European heat wave this week.",
  "IBM has built a new prototype chip with around 100 billion transistors on an area the size of a fingernail, which is twice the density of the company’s previous state-of-the-art technology announced in 2021. The design could pave the way for faster and more energy efficient computers for years to…",
  "Europe is in the middle of a record-breaking heat wave, and the grid is being pushed to its limits as people turn to fans and air-conditioning to try to stay cool. Some power plants won’t be online to help handle the load.",
  "Plus: China has taken the US’s crown for the world’s fastest supercomputer. June 24, 2026 Introducing: the Engineering issue We can’t fix everything, but we can be ambitious.",
  "Intercept, a new nonprofit, will focus on countering the common cold and the flu. June 24, 2026 Photo illustration by Sarah Rogers/MITTR | Photos Shutterstock The common cold comes for us all—often more than once a year.",
  "Credits Houda Nait El Barj is a researcher at OpenAI focused on advancing AI systems that support human flourishing. Editor’s Note: Noema is transparent about AI use in its pieces.",
  "Complex systems can engender the opposite outcome of intentions. Ibrahim Rayintakath for Noema Magazine Credits Nathan Gardels is the editor-in-chief of Noema Magazine.",
  "Credits Joshua Craze writes for The New York Review of Books, n+1, The Baffler and the Boston Review, among other publications. He is a fellow at Type Investigations and the Centre on Armed Groups.",
  "Credits Henry Wismayer is a writer based in London. LONDON — On the corner of a busy gyratory, a bus ride from my house in south London, sits an unremarkable yellow-brick building.",
  "Credits Nathan Gardels is the editor-in-chief of Noema Magazine. He is also the co-founder of and a senior adviser to the Berggruen Institute.",
  "Credits Ryan Huling is a writer and explorer focusing on animals, food and technology. He is a senior writer at the Good Food Institute Asia Pacific and the author of “The Hidden Nations of Animals.",
  "Last month, I was fortunate to participate in an event hosted by Open to Debate , a one-hour weekly program broadcast on National Public Radio stations across the country, and the SNF Agora Institute at Johns Hopkins University. The participants considered the question: “Is the scientific enterprise too risk-averse?",
  "completed Limiting screen time for children Episode 260618 / 18 Jun 2026 Children are spending too much time with electronic devices. completed How advertisers make us spend money Episode 260611 / 11 Jun 2026 When was the last time you bought something you didn't need?",
  "Easy English about moving house Practise listening and learn vocabulary UK prime minister resigns Learn expressions with 'deal' Try our study tips! Listening Speaking Reading Learn to talk about where you live All our topic pages Learn English for work Listen to reports from BBC News Stress-free family meals Limiting…",
  "Improve your grammar Learn grammar by listening Listen to our 'Learning English Grammar' podcast to learn the grammar you need to speak English confidently. Grammar with Georgie English grammar can be difficult, let Georgie make it easy for you in these fun, short video series Learn grammar by reading Remind…",
  "Easy English: The London Letter Challenge Easy English: The London to Edinburgh Challenge English My Way: Easy English for everyday life Real Easy English Lower-intermediate course Develop your English Enhance your English Better English skills Be a successful distance learner Learn English from Shakespeare Join Tim as he takes you…",
  "Improve your speaking and pronunciation skills with these programmes. The latest episode Discover the series Speak better in five days Improve your pronunciation How to speak English more fluently How to be polite in English Practise reading articles with The Reading Room, or improve your academic reading skills with Go…",
  "Learn the English you need to work in an office in these episodes of our Learning English for Work podcast Latest episode All Episodes Learn easy English to talk about work and jobs Easy English about work Easy English about the office Work: What can you do? Easy English about…",
  "Learn English from the news Latest news episodes Learn the English you need to understand the latest news stories News series Learn English from news headlines in Learning English from the News. Improve your listening skills with radio reports in The Listening Room and learn to identify disinformation in Fake…",
];

/** Harvested + synthetic boilerplate / ad-copy negatives (SHORT). */
export const HARVESTED_AD_SAMPLES: readonly string[] = [
  "NBC News Now · Nightly Films · Stay Tuned · Special Features · Newsletters · Podcasts · Listen Now · Business in America",
  "NBC. COM · NBCU Academy · Peacock · NEXT STEPS FOR VETS · NBC News Site Map · Help · Facebook · Twitter",
  "Africa · Asia · Europe · Matias Delacroix / AP · Venezuela earthquake death toll rises above 1,400 · Reuters · IRAN WAR · Data Graphics",
  "Donald Trump · White House · Congress · Wayan Barre / Bloomberg via Getty Images · 2026 ELECTION · Nathan Laine / Bloomberg via Getty Images · Getty Images; AP · 2026 Election",
  "Jim Watson / Pool via Getty Images · Trump administration · CQ-Roll Call / Bill Clark/CQ-Roll Call / Sipa USA · Elections · Getty Images · Supreme Court · Brad Vest for NBC News · NASA / Getty Images file",
  "Environment · Deaths from this cancer can now be virtually eliminated · Health · 8 night sky events to see in July · Science · A river crisis is unfolding in the American West · Environment · How a Nat Geo photographer learned to live on Mars",
  "Photography · Animals · Science · Science · Science · Health · Environment · Why strength training advice for women is mostly wrong",
  "Terror birds survived millions of years longer than thought · Science · How caring for a child may reshape your brain · Health · Why existing vaccines won’t help the Ebola outbreak · Health · load more · Terms of Use",
  "Environment · A river crisis is unfolding in the American West · Environment · Environment · Environment · Glimpsing the future of fresh food · Environment · Environment",
  "Environment · Environment · Science · Science · Why the heat index matters more than just the temperature · Environment · Environment · What a ‘super’ El Niño means for the planet",
  "Environment · Environment · Scientists just found the 'Sasquatch' of the sea · Environment · load more · Terms of Use · Privacy Policy · Your US State Privacy Rights",
  "Children's Online Privacy Policy · Interest-Based Ads · About Nielsen Measurement · Do Not Sell or Share My Personal Information · Nat Geo Home · Attend a Live Event · Book a Trip · Buy Maps",
  "Climate · Skip to Content · Subscribe · The World Cup Pride Match Is A Winner · World · How to Help Victims of the Venezuela Earthquakes · Politics · Ideas",
  "How AI Will Make Art Worse · Ideas · The Crisis I Witnessed in Haiti · Terms of Service · Privacy Policy · The Story Behind TIME’s 250th Anniversary of America Issue · Our America · U. S.",
  "Read More · Entertainment · 'The Bear's' Final Season Belongs to Sydney · Ideas · America's New, Old Attitude Toward 'Foreign Entanglements' · Health · People Are Living Better at the End of Their Lives · Entertainment",
  "get the issue · Access The Vault · Our America Our America · Read More · Lebron James · Greta Lee · Erling Haaland · Idris Elba and Sabrina Dhowre Elba",
  "Skip to Content · Subscribe · Go to your personalized feed · Account Settings · Health · Go to your personalized feed · Account Settings · Entertainment",
  "Go to your personalized feed · Account Settings · How to Help Victims of the Venezuela Earthquakes · How to Help Victims of the Venezuela Earthquakes · Iran · Iran · Iran · Iran",
  "extreme weather · Why Is Europe So Ill-Equipped to Handle Heat Waves? · extreme weather · Venezuela · Venezuela · WORLD · The Story I Went Searching For—and the One That Found Me · IDEAS",
  "Black Voices · Queer Voices · Latino Voices · Indigenous Voices · Asian Voices · Women's Voices · Voices of Disabled People · HuffPost Personal",
  "The Democratic Insurgency Is Sweeping Through Colorado · This Simple Oral Sex Hack Is Going Viral · 21 Years of The Huffington Post · NEWS · POLITICS · ENTERTAINMENT · 🛍️ PRIME DAY DEALS 🛍️ · LIFE",
  "This Simple Oral Sex Hack Is Going Viral · 21 Years of The Huffington Post · NEWS · POLITICS · ENTERTAINMENT · 🛍️ PRIME DAY DEALS 🛍️ · LIFE · PERSONAL",
  "Business · World of Business · Technology of Business · NYSE Opening Bell · Technology · Artificial Intelligence · Intelligence Revolution · AI v the Mind",
  "Australia and Pacific · Caribbean & Bermuda · Central America · Europe · Middle East · North America · South America · World’s Table",
  "Weather · BBC Shop · BritBox · BBC News Brasil · BBC News Mundo (Spanish) · BBC News မြန်မာ (Burmese) · BBC News 中文 (Chinese) · BBC News Indonesia",
  "BBC News 코리아 (Korean) · BBC News ไทย (Thai) · BBC News Tiếng Việt (Vietnamese) · BBC News Azərbaycanca (Azeri) · BBC News Magyarul (Hungarian) · BBC News Кыргыз Кызматы (Kyrgyz) · BBC News Polska (Polish) · BBC News România (Romanian)",
  "Artificial Intelligence · Intelligence Revolution · AI v the Mind · Tech Now · Home · News · US & Canada · UK Politics",
  "BBC InDepth · BBC Verify · Football 2026 · Sport · Business · World of Business · Technology of Business · NYSE Opening Bell",
  "Technology · Artificial Intelligence · Intelligence Revolution · AI v the Mind · Tech Now · Health · Culture · Film & TV",
  "Middle East · North America · South America · World’s Table · Culture & Experiences · Adventures · The SpeciaList · Earth",
  "Subscribe to Smithsonian magazine and get a FREE tote. · Human Behavior · Mind & Body · Our Planet · Space · Wildlife · Newsletter · Olivia Ferrari",
  "Privacy Notice · Terms & Conditions · Can Printed ‘Skin’ Heal Burns and Prevent Scars? · America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark · Based on a True Story",
  "Arts & Culture · Travel · At the Smithsonian · Photo Contest · Podcast · Video · Subscribe · Give a gift",
  "Smithsonian Channel · Smithsonian Books · Smithsonian Membership · Privacy Statement [5/20/25] · Cookie Policy [5/20/25] · Terms of Use · Advertising Notice · Your Privacy Choices",
  "Terms & Conditions · America's 250th Anniversary · America's 250th Anniversary · America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark",
  "America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark · America at 250: The Revolutionary Spark · ... · 300 · 301 · Next · National Museum of the American Indian",
  "Smithsonian American Women's History Museum · National Museum of American History · Smithsonian Education · Smithsonian American Women's History Museum · Office of the Secretary of the Smithsonian · More Smithsonian Voices · Smart News · History",
  "Skip to content · cookies · CANCEL · Health & Disease · Living World · Physical World · Society · Food & Environment",
  "Story Behind a Picture · Videos · Building Bodies · Persuasion · Special Report: Reset · The Working Life · DONATE · About",
  "Society · Food & Environment · Technology · The Mind · CLIMATE CHANGE · English · Physical World · Food & Environment",
  "Lindzi Wessel · M. Mitchell Waldrop · John Wenz · Adam Mann · Anil Ananthaswamy · More (65) · Less · Physical World",
  "Sustainability · More (43) · Less · M. Mitchell Waldrop · Bob Holmes · Amber Dance · Katarina Zimmer · Nicola Jones",
  "AI shows promise in the fight against fake news · Technology · How will AI make moral decisions for you and me? · Technology · Can printed ‘skin’ help to heal burns without scars?",
  "Topics · Newsletters · Events · Audio · Terms of Service · Privacy Policy · All topics · READ ABOUT OUR HISTORY",
  "ADVERTISE WITH US · About us · Careers · Custom content · Advertise with us · International Editions · Republishing · MIT Alumni News",
  "Help & FAQ · My subscription · Editorial guidelines · Privacy policy · Terms of Service · Write for us · Contact us · linkedin opens in a new window",
  "instagram opens in a new window · reddit opens in a new window · facebook opens in a new window · rss opens in a new window",
  "Skip to the content · Subscribe · Published by the Berggruen Institute · Technology & the Human · Future of Capitalism · Philosophy & Culture · Climate Crisis · Geopolitics & Deglobalization",
  "Future of Democracy · Digital Society · Read Noema In Print · Show filters · Hide filters · Clear All · Last month · Last year",
  "Custom · Essay · Technology & the Human · How AI Will Change Us · Houda Nait El Barj · Feature · Geopolitics & Globalization · The Mars Delusion",
  "Henry Wismayer · Essay · Geopolitics & Globalization · The Warfare Of The Future Is Already Here · Nathan Gardels · Interview · Geopolitics & Globalization · Eric Schmidt",
  "Custom · Essay · Future of Capitalism · The Next US Presidential Election Will Be About AI · Nathan Gardels · Essay · Future of Capitalism · ‘This Is Not Financial Advice’",
  "James O'Sullivan · Essay · Future of Capitalism · Pope Leo: AI Wealth Must Be Universally Shared · Nathan Gardels · Essay · Technology & the Human · How To Future-Proof Your Career In The Age Of AI",
  "The Latest Explore · Stories Read · Multimedia Look · The Podcast Listen · Academia · Climate Change · Coronavirus · Drugs & Addiction",
  "Environment & Conservation · Fish & Wildlife · Health & Medicine · Math & Physics · Natural Sciences · Science Policy · Social Sciences · Space & Astronomy",
  "Technology & Innovation · Support Undark · Meet Our Team · Newsletters · Contact Us · Submit a Proposal · AI Policy · Using Our Stories",
  "Listen · Menu · About · Viewpoints · Opinion: What I Learned from Teaching Darwin · C. Brandon Ogbunu · Interviews · Interview: Christopher Borgert on Glyphosate Drama",
  "Listen · Menu · About · News & Features · A More Troubling Picture of Sea Level Rise · Fred Pearce · Yale Environment 360 · Books",
  "Earth · Audio · Video · Live · Close menu · Learning English · Inspiring language learning since 1943 · English Change language",
  "Home · Home Home · Pronunciation Home · Vocabulary Home · Grammar Home · Courses Home · Skills Home · Work English Home",
  "News Home · Level · Easy Level · Medium Level · Hard Level · Topics · Food Topics · Feelings and emotions Topics",
  "The environment Topics · Friends and family Topics · Travel and transport Topics · All topics Topics · Latest · Latest Latest · Downloads Latest · Podcasts",
  "We use cookies and similar technologies to personalize content and ads, provide social media features, and analyze our traffic. By clicking accept you consent to the storing of cookies on your device.",
  "Sign up for our free newsletter and get the day's top stories delivered to your inbox every morning. Enter your email address below to subscribe.",
  "Subscribe to the newsletter for weekly highlights, exclusive interviews, and behind-the-scenes stories from our editors. Enter your email to join thousands of readers who never miss an update.",
  "Home News World Politics Business Science Health Technology Sports Opinion Culture Travel Weather Video Podcasts Newsletters Login Subscribe Search Menu About Contact Careers Privacy Terms",
  "Your free trial is about to expire. Upgrade to a premium subscription to keep unlimited access to all our articles, archives, and apps.",
  "Order now and enter your email to receive special offers straight to your inbox every day. Use promo code SAVE at checkout.",
  "Hurry, sale ends soon to win a brand new phone — you are our lucky visitor, confirm your details now. Money back guarantee.",
  "Don't miss out to win a brand new phone — you are our lucky visitor, confirm your details now. Limited stock, hurry.",
  "Buy today to win a brand new phone — you are our lucky visitor, confirm your details now. Shop in store or online.",
  "Hurry, sale ends soon and enter your email to receive special offers straight to your inbox every day. No credit card required.",
  "Save big today before stock runs out — lowest prices guaranteed, buy one get one free. Use promo code SAVE at checkout.",
  "Hurry, sale ends soon and upgrade to premium to remove ads and read without limits, cancel anytime. Use promo code SAVE at checkout.",
  "Act fast to win a brand new phone — you are our lucky visitor, confirm your details now. Use promo code SAVE at checkout.",
  "Hurry, sale ends soon and save up to 60% on your first order with free shipping on everything. Shop in store or online.",
  "Subscribe now to win a brand new phone — you are our lucky visitor, confirm your details now. No credit card required.",
  "Buy today and save up to 60% on your first order with free shipping on everything. Use promo code SAVE at checkout.",
  "Save big today to win a brand new phone — you are our lucky visitor, confirm your details now. No credit card required.",
  "Limited time offer to win a brand new phone — you are our lucky visitor, confirm your details now. Free returns, no risk.",
  "Hurry, sale ends soon and get a free gift while supplies last — this offer expires at midnight. Use promo code SAVE at checkout.",
  "Save big today and enter your email to receive special offers straight to your inbox every day. Shop in store or online.",
  "Shop now to win a brand new phone — you are our lucky visitor, confirm your details now. Offer valid today only.",
  "Hurry, sale ends soon to claim your coupon, redeem your points, and start saving on every purchase. Shop in store or online.",
  "Join now to win a brand new phone — you are our lucky visitor, confirm your details now. Offer valid today only.",
];

/** Genuine article prose samples (seed + harvested). */
export const ARTICLE_SAMPLES: readonly string[] = [
  ...SEED_ARTICLE_SAMPLES,
  ...HARVESTED_ARTICLE_SAMPLES,
];

/** Ad / junk / navigation / boilerplate samples (seed + harvested). */
export const AD_SAMPLES: readonly string[] = [...SEED_AD_SAMPLES, ...HARVESTED_AD_SAMPLES];
