import type { Metadata } from "next";
import { terms } from "@/lib/copy/pages";
import { LegalPageShell } from "@/components/legal/LegalPageShell";

export const metadata: Metadata = terms;

const SECTION_HEADING_CLASS =
  "font-[family-name:var(--font-display)] font-semibold text-[length:var(--text-xl)] text-text";

const termsSections = [
  {
    heading: "1. Acceptance of terms",
    body: (
      <>
        By accessing or using ReadWise (&ldquo;the Service&rdquo;), you agree to be bound by
        these Terms of Service. If you do not agree, please do not use the Service.
      </>
    ),
  },
  {
    heading: "2. Use of the service",
    body: (
      <>
        ReadWise is an AI-assisted English learning reader for personal, non-commercial use. You
        agree not to misuse the Service, attempt to circumvent access controls, or use automated
        tools to scrape or abuse the platform. ReadWise reserves the right to suspend accounts
        that violate these terms.
      </>
    ),
  },
  {
    heading: "3. Content",
    body: (
      <>
        Articles displayed in ReadWise are sourced from third-party news publishers and are used
        for educational purposes. Copyright in individual articles remains with the original
        publishers. ReadWise does not claim ownership of any third-party content.
      </>
    ),
  },
  {
    heading: "4. AI-generated content",
    body: (
      <>
        Features such as translations, vocabulary lists, comprehension quizzes, and difficulty
        assessments are generated by AI models and may contain errors. They are provided for
        educational assistance only and should not be relied upon as authoritative references.
      </>
    ),
  },
  {
    heading: "5. Accounts",
    body: (
      <>
        You are responsible for maintaining the security of your account. You must notify us
        immediately if you suspect unauthorised access. ReadWise reserves the right to terminate
        accounts that violate these terms or are inactive for extended periods.
      </>
    ),
  },
  {
    heading: "6. Disclaimer of warranties",
    body: (
      <>
        The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not
        guarantee continuous availability, accuracy of AI outputs, or fitness for a particular
        purpose. Use of the Service is at your own risk.
      </>
    ),
  },
  {
    heading: "7. Changes to terms",
    body: (
      <>
        We may update these terms from time to time. Continued use of ReadWise after changes are
        posted constitutes acceptance of the revised terms.
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPageShell heading="Terms of Service" lastUpdated="Last updated: June 2025">
      {termsSections.map(({ heading, body }) => (
        <section key={heading}>
          <h2 className={SECTION_HEADING_CLASS}>{heading}</h2>
          <p className="text-text-muted">{body}</p>
        </section>
      ))}
    </LegalPageShell>
  );
}
