/**
 * Generate compact English word-frequency ranks for deterministic difficulty.
 *
 * Source data is the `aparrish/wordfreq-en-25000` JSON export, which is derived
 * from Robyn Speer's upstream `wordfreq` English data. The generated runtime
 * file stores only a filtered top-10k alphabetic rank list used to assign broad
 * frequency bands (`top1k`, `top2k`, `top3k`, `top5k`, `top10k`).
 *
 * Usage:
 *   npm run wordfreq:generate
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

const SOURCE_URL =
  "https://raw.githubusercontent.com/aparrish/wordfreq-en-25000/main/wordfreq-en-25000-log.json";
const OUTPUT_PATH = path.resolve(process.cwd(), "src/data/wordfreq-en-ranks.ts");
const LIMIT = 10_000;

type WordfreqRow = [word: string, logFrequency: number];

function normalizeWord(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const word = value.toLowerCase();
  if (!/^[a-z]+$/.test(word)) return null;
  if (word.length === 1 && word !== "a" && word !== "i") return null;
  return word;
}

function buildTopWords(rows: WordfreqRow[]): string[] {
  const seen = new Set<string>();
  const words: string[] = [];

  for (const row of rows) {
    const word = normalizeWord(row[0]);
    if (!word || seen.has(word)) continue;
    seen.add(word);
    words.push(word);
    if (words.length >= LIMIT) break;
  }

  if (words.length < LIMIT) {
    throw new Error(`Expected at least ${LIMIT} filtered words, got ${words.length}.`);
  }

  return words;
}

function renderWordList(words: string[]): string {
  const chunks: string[] = [];
  for (let i = 0; i < words.length; i += 8) {
    chunks.push(`  ${words.slice(i, i + 8).map((word) => JSON.stringify(word)).join(", ")}`);
  }
  return chunks.join(",\n");
}

async function fetchRows(): Promise<WordfreqRow[]> {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${SOURCE_URL}: ${response.status} ${response.statusText}`);
  }
  const data = (await response.json()) as unknown;
  if (!Array.isArray(data)) {
    throw new Error("Expected wordfreq export to be a JSON array.");
  }
  return data as WordfreqRow[];
}

async function main(): Promise<void> {
  const rows = await fetchRows();
  const words = buildTopWords(rows);
  const content = `/**
 * Generated by scripts/generate-wordfreq-ranks.ts. Do not edit by hand.
 *
 * Source: ${SOURCE_URL}
 * The source export is derived from Robyn Speer's wordfreq English data.
 * wordfreq code is Apache-2.0; the bundled frequency data includes
 * CC BY-SA 4.0-redistributable sources. Keep docs/platform/supply-chain.md
 * attribution notes in sync when this file is regenerated or replaced.
 */

export const WORDFREQ_EN_TOP_10K: readonly string[] = [
${renderWordList(words)},
];
`;

  writeFileSync(OUTPUT_PATH, content, "utf-8");
  console.log(`Wrote ${words.length} words to ${path.relative(process.cwd(), OUTPUT_PATH)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});