/**
 * Reader preference no-flash bootstrap script (REF-029, REF-055).
 *
 * Renders an inline `<script>` that reads the `readwise:reader-prefs`
 * localStorage key and applies the saved reading mode, font scale, font
 * family, and line spacing to `#reader-root` before the first paint —
 * preventing a flash of the default (un-preferenced) appearance.
 *
 * The script text is generated by `buildBootstrapScript()` from
 * `@/lib/reader-prefs` so it stays co-located with the preference schema and
 * can be independently tested.
 *
 * Placement requirement: this component MUST be the first child of
 * `#reader-root`. `document.currentScript.parentElement` resolves to the
 * element BEFORE any of its children are painted. Using `getElementById`
 * instead would fail because the script executes before `#reader-root`
 * finishes parsing.
 *
 * The parent element carries `suppressHydrationWarning` because this script
 * mutates the element's `data-*` attributes and CSS custom properties during
 * pre-hydration, which would otherwise trigger a React hydration mismatch
 * warning on client restore.
 */
import { buildBootstrapScript } from "@/lib/reader-prefs";

export default function ReaderPrefsScript() {
  return (
    <script dangerouslySetInnerHTML={{ __html: buildBootstrapScript() }} />
  );
}
